### ISSUE TITLE
Unable to load package modules

### ISSUE THREAD

**Issue by marcianito** [oelsmann/discotimes#2]
Hi,

thanks for this piece of software! It sounds really cool and I wanted to test and try it straight away when I read about it.
Sadly this is not working out. I thought maybe you have a "perfect setup" that would help it.

I tried on different machines, both Linux and windows.
Python 3.9 and 3.10
Different versions of numpy (as this is part of the error I guess).

E.g. running:
```
from discotimes.discotimes import file_reader 
````

I always get the following error:
```
module 'numpy.distutils.__config__' has no attribute 'blas_opt_info'
```

Did anyone experience the same or similar and knows a fix?
Which numpy version is working well for this?

Would be highly appreciated!

Thanks already! :)

**Comment by marcianito** [comment]
Hello,

trying out some more I found a working numpy version and setup: numpy 1.21
so workaround would be `pip install --upgrade numpy==1.21`
as suggested and explained here:
https://stackoverflow.com/questions/70839312/module-numpy-distutils-config-has-no-attribute-blas-opt-info
it apparently has to do with theano, which is also used in distrotimes.

**Comment by oelsmann** [comment]
Hi,

thanks a lot for noting this issue!
You're right, numpy should be <1.22
I added that information in the requirements.txt file!

Thanks!
